apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-burner-metrics-pvc
  namespace: kube-burner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi